### ISSUE TITLE
Firefox behind firewall  with blocked udp not working

### ISSUE THREAD

**Issue by so010** [edumeet/edumeet#72] opened 2018-10-31 13:07 UTC
If Firefox has to use TCP (via TURN or directly to mediasoup-server) there will no mediastreams go to or from client.

Problem is that there are different ICE candidates used on server and client:

Firefox: receive:
![screenshot from 2018-10-31 13-41-43](https://user-images.githubusercontent.com/966197/47788713-cf305080-dd12-11e8-80dd-f27ebe73a030.png)
[firefox-receive.log](https://github.com/havfo/multiparty-meeting/files/2534449/firefox-receive.log)

Firefox send:
![screenshot from 2018-10-31 13-42-57](https://user-images.githubusercontent.com/966197/47788758-ed964c00-dd12-11e8-8a86-fb0cfa750485.png)
[firefox-send.log](https://github.com/havfo/multiparty-meeting/files/2534450/firefox-send.log)

mediasoup server:
[21598298.log](https://github.com/havfo/multiparty-meeting/files/2534401/21598298.log)
[44260674.log](https://github.com/havfo/multiparty-meeting/files/2534404/44260674.log)

As you can see Firefox has nominated and selected TCP candidates while mediasoup uses udp candidates. 

Actually mediasoup sends streams to Firefox but firewall is blocking. 
Transport for receive on mediasoup side is timing out with a dtls failure after 30 secs.
{"roomId":10882856,"peerName":"kgm2bxmq","transportId":44260674,"event":"transport.dtlsstatechange","dtlsState":"failed","timestamp":1540978250225}

**Comment by so010** [comment] 2018-10-31 13:10
This is most likely a bug in mediasoup and a big problem because Firefox users can't connect to room if they are behind a udp-blocking firewall.

**Comment by misi** [comment] 2018-10-31 14:19
I will try to check it..

**Comment by misi** [comment] 2018-11-01 09:16
What happens if you disable in firefox config the ICE tcp
so set in about:config the media.peerconnection.ice.tcp to false?
Does it solve it?

**Comment by misi** [comment] 2018-11-01 11:19
Check it with https://eper.lab.vvc.niif.hu it seems ok and runs correctly without udp with ice.tcp

**Comment by so010** [comment] 2018-11-01 16:57
Does not work for me. If I come with Firefox from our udp blocked net
not streams get through and Firefox says tcp(relayed) succeeded,
nominated and selected.

**Comment by misi** [comment] 2018-11-03 13:11
Strange. :-/

What I have tested and what works for me is the following: 
I have two FF tab connected to the same room, and I modeled the udp blocked network with -j DROP in INPUT and OUTPUT chain to and from the SFU (eper..).

So what could be the difference in your case? 

Longer delay because of the distance?

I am wondering how should I model better way the UDP drooping firewall? 
e.g. Does it send ICMP reject instead of DROP?

**Comment by havfo** [comment] 2018-11-06 11:54
I can reproduce the error with the following rules:

# Flush tables
iptables -F
iptables -X

# Default TCP allow established
iptables -A INPUT -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT

# Default allow DNS (udp)
iptables -A INPUT -p udp --sport 53 -j ACCEPT
iptables -A INPUT -p udp --dport 53 -j ACCEPT
iptables -A OUTPUT -p udp --sport 53 -j ACCEPT
iptables -A OUTPUT -p udp --dport 53 -j ACCEPT

# Block udp input
iptables -A INPUT -p udp -j DROP

# Default global policy
iptables -P INPUT DROP
iptables -P FORWARD DROP
iptables -P OUTPUT ACCEPT


Run all those in order and try using Firefox.

**Comment by havfo** [comment] 2018-11-06 11:54
You can make it work again by blocking all OUTPUT UDP:
# Block udp output
iptables -A OUTPUT -p udp -j DROP

**Comment by havfo** [comment] 2022-11-19 09:58
Fixed in new client/server

**Closed by havfo** 2022-11-19 09:58 UTC
Labels: misc/ bug
