### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Astagor** [edumeet/edumeet#890] opened 2021-07-27 11:09 UTC
Hi guys, I'm back after holidays. I have just tried to make a clean installation of the current develop branch, but the build fails:

npm i && npm run build

> react-scripts build && mkdir -p ../server/public && rm -rf ../server/public/* && cp -r build/* ../server/public/

Creating an optimized production build...
Failed to compile.

src/components/Containers/Me.js
  Line 525:45:  Unexpected use of comma operator  no-sequences
  Line 588:45:  Unexpected use of comma operator  no-sequences

src/components/LeaveDialog.js
  Line 177:48:  Unexpected use of comma operator  no-sequences

**Comment by roman-drozd-it** [comment] 2021-07-27 12:10
Confirmed. Have just tested and the same error using **npm** on **develop**. Labeled as bug.
Try to use **yarn**: `yarn && yarn build`. Should work.

Tested on:
```
node       14.15.4
 ↪ n       7.0.1
 ↪ npm     6.14.10
 ↪ yarn    1.21.1
```

**Comment by roman-drozd-it** [comment] 2021-07-27 13:05
Fixed by https://github.com/edumeet/edumeet/commit/2ee003e0f270e584a70d9b695dc4e995edd4d228 https://github.com/edumeet/edumeet/commit/f22ba20efa681b34ee36da9962f4c74fe11dc32c. Please test it.

**Comment by Astagor** [comment] 2021-07-27 13:32
It has fixed it, but now I get an error in the Chrome console:

Uncaught TypeError: a is not a function
    at _ (11.48254eb5.chunk.js:2)
    at P (11.48254eb5.chunk.js:2)
    at Object.9 (main.13ecc879.chunk.js:1)
    at f (test11:1)
    at Object.187 (main.13ecc879.chunk.js:1)
    at f (test11:1)
    at Module.<anonymous> (main.13ecc879.chunk.js:1)
    at Module.292 (main.13ecc879.chunk.js:1)
    at f (test11:1)
    at r (test11:1)

My config.js is:
// eslint-disable-next-line
var config = {};

**Comment by Astagor** [comment] 2021-07-27 14:54
This happens when building with NPM.
With YARN it works....

**Comment by roman-drozd-it** [comment] 2021-07-27 18:01
building with **npm** is definitely a problem.

**Comment by roman-drozd-it** [comment] 2021-07-28 01:00
fixed by https://github.com/edumeet/edumeet/commit/295b353f6127d25ef2c31f11f54f4eeecc46448e

For some reason there wasn't _package-lock.json_ inside the codebase (creating was disabled in _.npmrc_ and tracking was disabled in _.gitignore_)  what probably caused some problems with dependecies' consistency among different envs. So:

1. I created a new one based on _yarn.lock_ using a tool for that: `npm install -g synp`  `synp --source-file yarn.lock`
2. removed the existing excluding entry from .gitignore
3. `package-lock=false` -> `package-lock=true` in .npmrc
4. commited it

Now everything seems to be working as expected.
Need more test. @Astagor try to clone/install/build the edumeet using **npm** on your env.

**Comment by roman-drozd-it** [comment] 2021-07-28 02:55
More about how to correctly use/work/deal with a _package-lock.json_ (including `node ci` command)
https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5/56254478#56254478

**Comment by roman-drozd-it** [comment] 2021-09-13 20:20
seems to be working now.

**Closed by roman-drozd-it** 2021-09-13 20:20 UTC
Labels: misc/ bug
