### ISSUE TITLE
Enabling authenticated user

### ISSUE THREAD

**Issue by chinthakadeshapriya** [edumeet/edumeet#351] opened 2020-05-13 01:30 UTC
Can you please explain the process of enabling authenticated user in DEV version

**Comment by misi** [comment] 2020-05-13 08:16
Please check the server/config/config.example.js
especially the auth part, and the OIDC settings, and user mapping..
If you have any specific question let us know. 

We are busy with the new release and this question is too general to answer... sorry.

**Comment by cap19** [comment] 2020-05-13 14:00
> Can you please explain the process of enabling authenticated user in DEV version

As misi mentioned, the settings are in the config file.

First enable the login in the app/public/config/config.js file

Change 	loginEnabled    : false, to 	loginEnabled    : true

**Comment by chinthakadeshapriya** [comment] 2020-05-15 11:49
I need to get  login URL as the initial page before calling the room. Please let me know how It can be done ?

**Comment by havfo** [comment] 2020-05-15 15:04
This is a rewrite of the join logic. This is not something that can be configured.

**Comment by Mwogi** [comment] 2020-05-20 14:26
@chinthakadeshapriya I am interested on how this is activated as well. I can't get any specific tutorial on how to enable sign up of accounts. I have tried connecting it with Google authentication but it fails - actually crashes the server.

**Comment by cap19** [comment] 2020-05-20 16:12
How did you connect your server to Google? Did you create an app in the google developer console and get the client id and secret?

**Comment by Mwogi** [comment] 2020-05-20 19:07
> How did you connect your server to Google? Did you create an app in the google developer console and get the client id and secret?

Yes, that is exactly what I did @cap19 
I am trying to figure out how someone does this authentication end to end. Assuming I successfully add a server for authentication, how do I set the roles and how do I assign this to users? 
Perhaps a community page is overdue for Multiparty Meeting?

**Comment by cap19** [comment] 2020-05-20 22:35
Paste your config files. Let’s see what’s going on with it. 

In my opinion the user roles are quite well documented in the example config file.

**Comment by misi** [comment] 2020-05-21 19:34
I tested latest develop branch code, docker image with google OIDC auth and it works fine..

I use issuer url: https://accounts.google.com/
See:
* https://accounts.google.com/.well-known/openid-configuration

I used the following guide to get credential
* https://developers.google.com/identity/protocols/oauth2/openid-connect

These are my settings
``` js
oidc:
{
		// The issuer URL for OpenID Connect discovery
		// The OpenID Provider Configuration Document
		// could be discovered on:
		// issuerURL + '/.well-known/openid-configuration'

		issuerURL     : 'https://accounts.google.com/',
		clientOptions :
		{
				client_id       : 'XXXXXXXXXXX.apps.googleusercontent.com',
				client_secret   : 'XXXXXXXXXXX',
				scope           : 'openid email profile',
				redirect_uri    : 'https://YOURSERVERFQDN/auth/callback'
		}

}

**Comment by Mwogi** [comment] 2020-05-21 22:26
Thank you @misi!
I used Keycloak and the authentication part worked beautifully for me. Except that I am unable to figure out which interface to set roles - Moderator/Admin etc. I have set the roles on Keycloak but they don't apply on a user loggin in.

I understand you have closed this but your help would be greatly appreciated!

**Comment by havfo** [comment] 2020-05-21 22:34
The `userMapping` function is run when the user is authenticated, and/or when the user connects via socket.io. Take a look in the example config, you get a `userinfo` object that should contain all info about the user from Keycloak. Simply dump this out to console if you are not sure what it contains to find out which roles to apply.

As an example, this will give `MODERATOR` role to users with email ending with `@example.com`:
```
if (userinfo.email && userinfo.email.endsWith('@example.com'))
{
	peer.addRole(userRoles.MODERATOR);
}
```

**Comment by Mwogi** [comment] 2020-05-21 22:36
@havfo Yes, I have used this to match the email. But is the email the only match parameter that I can use to assign e.g. Admin role or Moderator role or Authenticated role? It looks limiting.

**Comment by havfo** [comment] 2020-05-21 22:43
No, use whatever you like. The userinfo object contains whatever you configure in Keycloak. As said, dump it out to console to inspect it if you are unsure. There are several examples in the example config of other things to map by.

**Comment by Mwogi** [comment] 2020-05-21 22:45
@havfo Thank you! Let me try this out. I am still trying to understand Keycloak fully. Will update on the experience once I am done

**Comment by Mwogi** [comment] 2020-05-22 10:46
@havfo @misi The user is successfully authenticated from Keycloak. I even added the specific roles in Keycload - (admin, authenticated, moderator, presenter). However, after successful authentication, Multiparty Meeting is stuck at this screen:
![image](https://user-images.githubusercontent.com/736488/82660142-7dbc1f00-9c32-11ea-8aed-795b99c64db3.png)

In config.js, this is the setting:
`userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@mtrh.go.ke'))
		{
			peer.addRole(userRoles.MODERATOR);
		}

		peer.addRole(userRoles.AUTHENTICATED);
	},`

**Comment by Mwogi** [comment] 2020-05-23 10:52
@havfo I connected with Google authentication and it behaves exactly the same as above meaning the problem is not on the authenticating server. Despite successfully authenticating a user, Multiparty Meeting does process the userinfo object. I am using the dev branch. Could there be an issue there?

**Comment by havfo** [comment] 2020-05-23 10:59
The console log statement will show up on the server. Start your server with `DEBUG=* npm start` and watch the logs.

**Comment by gunnurafi** [comment] 2020-11-19 20:30
helllo ,
   how can i add admin and moderator ,presenter and normal user .how to generate  Admin(URL), moderator(URL),Presenter(URL) and normal(URL).please help me out how to get this .

**Closed** 2022-11-19 09:48 UTC
Labels: misc/ info needed ⌛, feat/ auth
