### ISSUE TITLE
Microphone unmuted after network reconnection

### ISSUE THREAD

**Issue by hajoscher** [edumeet/edumeet#510] opened 2020-08-04 13:35 UTC
When being disconnected due to network issues whilst muted, 
the user is unmuted after being reconnected.
That is problematic since it might unmute the user unknowingly. 

Tested today on https://edumeet.geant.org/ while my network was bad.

**Comment by zhengxiaochuan-3** [comment] 2020-08-06 03:00
+1

**Comment by misi** [comment] 2020-08-06 07:26
In 3.3.0?

**Comment by misi** [comment] 2020-08-06 12:25
I think I see the root of the issue. Only settings is persistent. `Me` properties are not..

**Comment by misi** [comment] 2020-08-06 14:23
I was little bit wrong. `Me` Redux state also does not contain the manual mute status.
All in all AFAIU the issue is that we don't store audio video muted state in the persistent local storage.

**Comment by so010** [comment] 2020-09-11 20:07
Same for video mute

**Comment by misi** [comment] 2020-10-27 08:34
Fixed in https://github.com/edumeet/edumeet/commit/48baea3cf28a9ad501794a3205574bb9f9fb5357

**Closed by misi** 2020-10-27 08:34 UTC
Labels: bug
