### ISSUE TITLE
Select audio output device

### ISSUE THREAD

**Issue by vlzkonopatov** [edumeet/edumeet#474] opened 2020-06-10 07:18 UTC
When you select an output device (Bluetooth headset), switching is successful, but the sound level becomes very quiet and almost nothing is heard. Has anyone encountered such a problem? Android device.

**Comment by misi** [comment] 2020-06-12 22:13
I don't have experienced such issue and AFAIU it should be a local issue.

**Comment by Astagor** [comment] 2020-06-13 17:06
Issues with headsets are often caused by the vendor implementation of audio sinks on Android. On my OnePlus5 and a sunny BT headset it works fine, but the same headset on Samsung S7 does not.

**Comment by misi** [comment] 2020-08-04 08:48
I think it is more a browser issue then ours, so I close this issue now.
If you disagree, then please let me know and I will reopen it.

**Closed by misi** 2020-08-04 08:48 UTC
Labels: question
