### ISSUE TITLE
Please help me launch the project!!!!

### ISSUE THREAD

**Issue by eshpilevsky** [edumeet/edumeet#1098] opened 2024-09-07 05:59 UTC
@misi @havfo @so010 @N7Remus @roman-drozd-it 

Please help me launch the project, I need it very urgently! Everything started up for me, but the video doesn’t work in the conference! I really need it, I will be very grateful!
Here is the page where I deployed the project on the server: https://pokersecretcam.club

1) https://github.com/edumeet/edumeet/issues/1097
2) https://github.com/edumeet/edumeet/issues/1096
3) https://github.com/edumeet/edumeet/issues/1095

<img width="1728" alt="Снимок экрана 2024-09-07 в 10 58 35" src="https://github.com/user-attachments/assets/cba279b8-0817-42fc-bc48-2f01513b4c19">

**Comment by N7Remus** [comment] 2024-09-30 07:55
Duplicate of #1095

**Closed by N7Remus** 2024-09-30 07:55 UTC
