### ISSUE TITLE
How to setup project at local host?

### ISSUE THREAD

**Issue by callmemonky** [edumeet/edumeet#529] opened 2020-08-29 16:52 UTC
I followed the steps given in readme but couldnt start a meeting. And the error was "Unable to join the room" (everytime i click on audio only or audio and video button). Please help!

Tell me if I am missing something?

**Comment by pierguinzani** [comment] 2020-08-31 12:06
I had the same problem and managed to solve it by changing the ip there in the server settings, in WebRtcTransport for my local ip:

![image](https://user-images.githubusercontent.com/49373874/91717908-c9069780-eb68-11ea-9e9e-044847374790.png)

The code snippet looks like this:

![image](https://user-images.githubusercontent.com/49373874/91718133-30244c00-eb69-11ea-820e-4ca0fc2ba340.png)

**Comment by callmemonky** [comment] 2020-08-31 12:32
Hey, can I know exact steps you followed? From the starting how did you setup the project.

because I am still getting the same error.

**Comment by sraza295** [comment] 2020-08-31 14:58
@callmemonky .
Please share your screenshot what are you getting an error?

**Comment by pierguinzani** [comment] 2020-08-31 15:06
1) I cloned the repo and performed all of these steps:
![image](https://user-images.githubusercontent.com/49373874/91720485-9ca14a00-eb6d-11ea-9efe-802a4e5a8d67.png)

2) Then, I went to the  directory
```
/edumeet/server/certs
```
 and generated a new cert and private key with the following command:
```
openssl req -x509 -newkey rsa:4096 -keyout privkey.pem -out cert.pem -days 365 -nodes -subj '/CN=localhost' 
```
![image](https://user-images.githubusercontent.com/49373874/91723491-3834b980-eb72-11ea-90b9-32d6120882f0.png)
Generating these two files here in the certs folder
![image](https://user-images.githubusercontent.com/49373874/91724107-30294980-eb73-11ea-92b6-a0853f2bdbf3.png)
3) 
Soon after, I added a turn/stun server 
* If using coturn, you can generate a user and key with:
```
$ turnadmin -k -u <username> -p <password>
```
For testing purposes, use this:
```
	
		{
			urls : [
				'turn:numb.viagenie.ca'
			],
			username   : 'webrtc@live.com',
			credential : 'muazkh'
		}
	
```

My final server configuration file (configs / server / config.js) looks like this:

```
const os = require('os');
const userRoles = require('../userRoles');

const {
	BYPASS_ROOM_LOCK,
	BYPASS_LOBBY
} = require('../access');

const {
	CHANGE_ROOM_LOCK,
	PROMOTE_PEER,
	SEND_CHAT,
	MODERATE_CHAT,
	SHARE_SCREEN,
	EXTRA_VIDEO,
	SHARE_FILE,
	MODERATE_FILES,
	MODERATE_ROOM
} = require('../permissions');

// const AwaitQueue = require('awaitqueue');
// const axios = require('axios');

module.exports =
{

	// URI and key for requesting geoip-based TURN server closest to the client
	turnAPIKey    : 'examplekey',
	turnAPIURI    : 'turn:numb.viagenie.ca',
	turnAPIparams : {
		'uri_schema' 	: 'turn',
		'transport' 		: 'tcp',
		'ip_ver'    		: 'ipv4',
		'servercount'	: '2'
	},

	// Backup turnservers if REST fails or is not configured
	backupTurnServers : [
		{
			urls : [
				'turn:numb.viagenie.ca'
			],
			username   : 'webrtc@live.com',
			credential : 'muazkh'
		}
	],
	fileTracker  : 'wss://tracker.lab.vvc.niif.hu:443',
	redisOptions : {},
	// session cookie secret
	cookieSecret : 'T0P-S3cR3t_cook!e',
	cookieName   : 'new-edutech.sid',
	// if you use encrypted private key the set the passphrase
	tls          :
	{
		cert : `/home/pier/Documentos/edumeet/server/certs/cert.pem`,
		// passphrase: 'key_password'
		key  : `/home/pier/Documentos/edumeet/server/certs/key.pem`
	},
	// listening Host or IP
	// If omitted listens on every IP. ("0.0.0.0" and "::")
	//listeningHost					: 'localhost',
	// Listening port for https server.
	listeningPort         : 3443,
	// Any http request is redirected to https.
	// Listening port for http server.
	listeningRedirectPort : 8080,
	// Listens only on http, only on listeningPort
	// listeningRedirectPort disabled
	// use case: loadbalancer backend
	httpOnly              : false,
	// WebServer/Express trust proxy config for httpOnly mode
	// You can find more info:
	//  - https://expressjs.com/en/guide/behind-proxies.html
	//  - https://www.npmjs.com/package/proxy-addr
	// use case: loadbalancer backend
	trustProxy            : '',
	// This logger class will have the log function
	// called every time there is a room created or destroyed,
	// or peer created or destroyed. This would then be able
	// to log to a file or external service.
	/* StatusLogger          : class
	{
		constructor()
		{
			this._queue = new AwaitQueue();
		}
		// rooms: rooms object
		// peers: peers object
		// eslint-disable-next-line no-unused-vars
		async log({ rooms, peers })
		{
			this._queue.push(async () =>
			{
				// Do your logging in here, use queue to keep correct order
				// eslint-disable-next-line no-console
				console.log('Number of rooms: ', rooms.size);
				// eslint-disable-next-line no-console
				console.log('Number of peers: ', peers.size);
			})
				.catch((error) =>
				{
					// eslint-disable-next-line no-console
					console.log('error in log', error);
				});
		}
	}, */
	// This function will be called on successful login through oidc.
	// Use this function to map your oidc userinfo to the Peer object.
	// The roomId is equal to the room name.
	// See examples below.
	// Examples:
	/*
	// All authenicated users will be MODERATOR and AUTHENTICATED
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		peer.addRole(userRoles.MODERATOR);
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with the moderator role set in the userinfo
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('moderator')
		)
		{
			peer.addRole(userRoles.MODERATOR);
		}
		if (
			Array.isArray(userinfo.meet_roles) &&
			userinfo.meet_roles.includes('meetingadmin')
		)
		{
			peer.addRole(userRoles.ADMIN);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	}
	// All authenicated users will be AUTHENTICATED,
	// and those with email ending with @example.com
	// will also be MODERATOR
	userMapping : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.email && userinfo.email.endsWith('@example.com'))
		{
			peer.addRole(userRoles.MODERATOR);
		}
		peer.addRole(userRoles.AUTHENTICATED);
	},
	*/
	// eslint-disable-next-line no-unused-vars
	userMapping           : async ({ peer, roomId, userinfo }) =>
	{
		if (userinfo.picture != null)
		{
			if (!userinfo.picture.match(/^http/g))
			{
				peer.picture = `data:image/jpeg;base64, ${userinfo.picture}`;
			}
			else
			{
				peer.picture = userinfo.picture;
			}
		}

		if (userinfo.nickname != null)
		{
			peer.displayName = userinfo.nickname;
		}

		if (userinfo.name != null)
		{
			peer.displayName = userinfo.name;
		}

		if (userinfo.email != null)
		{
			peer.email = userinfo.email;
		}
	},
	// All users have the role "NORMAL" by default. Other roles need to be
	// added in the "userMapping" function. The following accesses and
	// permissions are arrays of roles. Roles can be changed in userRoles.js
	//
	// Example:
	// [ userRoles.MODERATOR, userRoles.AUTHENTICATED ]
	accessFromRoles : {
		// The role(s) will gain access to the room
		// even if it is locked (!)
		[BYPASS_ROOM_LOCK] : [ userRoles.ADMIN ],
		// The role(s) will gain access to the room without
		// going into the lobby. If you want to restrict access to your
		// server to only directly allow authenticated users, you could
		// add the userRoles.AUTHENTICATED to the user in the userMapping
		// function, and change to BYPASS_LOBBY : [ userRoles.AUTHENTICATED ]
		[BYPASS_LOBBY]     : [ userRoles.NORMAL ]
	},
	permissionsFromRoles : {
		// The role(s) have permission to lock/unlock a room
		[CHANGE_ROOM_LOCK] : [ userRoles.MODERATOR ],
		// The role(s) have permission to promote a peer from the lobby
		[PROMOTE_PEER]     : [ userRoles.NORMAL ],
		// The role(s) have permission to send chat messages
		[SEND_CHAT]        : [ userRoles.NORMAL ],
		// The role(s) have permission to moderate chat
		[MODERATE_CHAT]    : [ userRoles.MODERATOR ],
		// The role(s) have permission to share screen
		[SHARE_SCREEN]     : [ userRoles.NORMAL ],
		// The role(s) have permission to produce extra video
		[EXTRA_VIDEO]      : [ userRoles.NORMAL ],
		// The role(s) have permission to share files
		[SHARE_FILE]       : [ userRoles.NORMAL ],
		// The role(s) have permission to moderate files
		[MODERATE_FILES]   : [ userRoles.MODERATOR ],
		// The role(s) have permission to moderate room (e.g. kick user)
		[MODERATE_ROOM]    : [ userRoles.MODERATOR ]
	},
	// Array of permissions. If no peer with the permission in question
	// is in the room, all peers are permitted to do the action. The peers
	// that are allowed because of this rule will not be able to do this
	// action as soon as a peer with the permission joins. In this example
	// everyone will be able to lock/unlock room until a MODERATOR joins.
	allowWhenRoleMissing : [ CHANGE_ROOM_LOCK ],
	// When truthy, the room will be open to all users when as long as there
	// are allready users in the room
	activateOnHostJoin   : true,
	// When set, maxUsersPerRoom defines how many users can join
	// a single room. If not set, there is no limit.
	// maxUsersPerRoom    : 20,
	// Room size before spreading to new router
	routerScaleSize      : 40,
	// Socket timout value
	requestTimeout       : 20000,
	// Socket retries when timeout
	requestRetries       : 3,
	// Mediasoup settings
	mediasoup            :
	{
		numWorkers : Object.keys(os.cpus()).length,
		// mediasoup Worker settings.
		worker     :
		{
			logLevel : 'warn',
			logTags  :
			[
				'info',
				'ice',
				'dtls',
				'rtp',
				'srtp',
				'rtcp'
			],
			rtcMinPort : 40000,
			rtcMaxPort : 49999
		},
		// mediasoup Router settings.
		router :
		{
			// Router media codecs.
			mediaCodecs :
			[
				{
					kind      : 'audio',
					mimeType  : 'audio/opus',
					clockRate : 48000,
					channels  : 2
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP8',
					clockRate  : 90000,
					parameters :
					{
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/VP9',
					clockRate  : 90000,
					parameters :
					{
						'profile-id'             : 2,
						'x-google-start-bitrate' : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '4d0032',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				},
				{
					kind       : 'video',
					mimeType   : 'video/h264',
					clockRate  : 90000,
					parameters :
					{
						'packetization-mode'      : 1,
						'profile-level-id'        : '42e01f',
						'level-asymmetry-allowed' : 1,
						'x-google-start-bitrate'  : 1000
					}
				}
			]
		},
		// mediasoup WebRtcTransport settings.
		webRtcTransport :
		{
			listenIps :
			[
				// change 192.0.2.1 IPv4 to your server's IPv4 address!!
				{ ip: '192.168.1.3', announcedIp: null }

				// Can have multiple listening interfaces
				// change 2001:DB8::1 IPv6 to your server's IPv6 address!!
				// { ip: '2001:DB8::1', announcedIp: null }
			],
			initialAvailableOutgoingBitrate : 1000000,
			minimumAvailableOutgoingBitrate : 600000,
			// Additional options that are not part of WebRtcTransportOptions.
			maxIncomingBitrate              : 1500000
		}
	}
	// Prometheus exporter
	/*
	prometheus: {
		deidentify: false, // deidentify IP addresses
		numeric: false, // show numeric IP addresses
		port: 8889, // allocated port
		quiet: false // include fewer labels
	}
	*/
};
```

**Comment by pierguinzani** [comment] 2020-08-31 15:08
Try to retrace my steps and see if it solves your problem

**Comment by callmemonky** [comment] 2020-09-01 03:44
@pierguinzani damn man! You're a savior. It worked now.

**Comment by callmemonky** [comment] 2020-09-01 04:44
@pierguinzani how do I make changes into app, mainly UI of conference screens(w hot reloading) ?

I tried but everytime I had to build again.

**Comment by sraza295** [comment] 2020-09-01 04:48
@callmemonky 
cd app 
npm start

--------

cd server
npm start


Now you will get hot reloading.

**Comment by callmemonky** [comment] 2020-09-01 05:20
@sraza295 so I did that, but I can get past that Room Screen.

How am i suppose to make changes to the conferences screen, I mean customizations and even add features

**Comment by callmemonky** [comment] 2020-09-01 05:30
Adding to above comment.

This is the console log.

![Screenshot from 2020-09-01 10-59-09](https://user-images.githubusercontent.com/25193916/91798311-3e926680-ec42-11ea-8c58-5605984bcb0f.png)

**Comment by havfo** [comment] 2020-09-01 05:51
To be able to have hot reloading work and do testing you have to accept the server certificate for the websocket. Usually the app starts on port 4443 for testing, and in the screenshot above the server is listening on port 3443. You need to visit the server directly on port 3443 once, and accept the certificate there as well, then the socket connection will go through.

**Comment by callmemonky** [comment] 2020-09-01 06:24
@havfo can you be more specific to the above solution?
When I am going to the 3443 port, it says "Site can't be reached", then how am I suppose to accept the server certificate?

**Comment by havfo** [comment] 2020-09-01 06:48
A simple way of doing it is doing a `npm run build` of the app, and then run the server. You should then be able to visit the server like you tried.

**Comment by pierguinzani** [comment] 2020-09-01 12:18
I'm glad I helped solve your problem. I think it would be interesting to close the issue and open another one with this topic that you mentioned :)

**Comment by callmemonky** [comment] 2020-09-01 17:05
> > @pierguinzani how do I make changes into app, mainly UI of conference screens(w hot reloading) ?
> > 
> > I tried but everytime I had to build again.
> 
> I'm glad I helped solve your problem, @callmemonky.  I think it would be interesting to close the issue and open another one with this topic that you mentioned :) 

Hey btw....did you deploy it on virtual private server?

I have opened another issue, maybe you can help.

**Comment by asim47** [comment] 2020-09-04 08:48
Hi,

Im getting this error when i start the server.
![image](https://user-images.githubusercontent.com/47098243/92220301-3d1ca480-eeb5-11ea-854b-8c92750d0b21.png)

**Comment by asim47** [comment] 2020-09-04 10:22
after following @pierguinzani 's guide, i ended up here, cant continue from here, when i visit localhost:3443 i get localhost didn’t send any data. what am i missing?
![image](https://user-images.githubusercontent.com/47098243/92229043-4b24f200-eec2-11ea-9e02-689998f8aea6.png)

**Comment by pierguinzani** [comment] 2020-09-04 10:39
> after following @pierguinzani 's guide, i ended up here, cant continue from here, when i visit localhost:3443 i get localhost didn’t send any data. what am i missing?
> ![image](https://user-images.githubusercontent.com/47098243/92229043-4b24f200-eec2-11ea-9e02-689998f8aea6.png)

Hey, @asim47. Try to open the address https: // localhost: 443

**Comment by asim47** [comment] 2020-09-04 10:41
> > after following @pierguinzani 's guide, i ended up here, cant continue from here, when i visit localhost:3443 i get localhost didn’t send any data. what am i missing?
> > ![image](https://user-images.githubusercontent.com/47098243/92229043-4b24f200-eec2-11ea-9e02-689998f8aea6.png)
> 
> Hey, @asim47. Try to open the address https://localhost:443

I get This site can’t be reached

**Comment by asim47** [comment] 2020-09-04 10:42
listeningHost					: 'localhost',
	// Listening port for https server.
	listeningPort         : 3443,
	// Any http request is redirected to https.
	// Listening port for http server.
	listeningRedirectPort : 8080,

Im using these ports

**Comment by pierguinzani** [comment] 2020-09-04 10:44
Make sure the file app/public/config/config.js follows these settings
![image](https://user-images.githubusercontent.com/49373874/92230869-2e68ca00-ee82-11ea-82ca-40fe66c58427.png)

**Comment by asim47** [comment] 2020-09-04 10:48
> Make sure the file app/public/config/config.js follows these settings
> ![image](https://user-images.githubusercontent.com/49373874/92230869-2e68ca00-ee82-11ea-82ca-40fe66c58427.png)

app/public/config/config.js file is exactly as you provided.

the server/config/config.js is
![image](https://user-images.githubusercontent.com/47098243/92231298-f8e5d000-eec5-11ea-9f14-0cc640c136e7.png)


and now when i visit https://localhost:3443 i get this
![image](https://user-images.githubusercontent.com/47098243/92231355-0bf8a000-eec6-11ea-951d-a9bc6c4afa19.png)

I have generated new cert.pem and privkey.pem.

Thanks,

**Comment by pierguinzani** [comment] 2020-09-04 10:51
Just do it now
![image](https://user-images.githubusercontent.com/49373874/92231618-6e7c7c80-ee83-11ea-9457-41efd6bfeac1.png)

**Comment by asim47** [comment] 2020-09-04 10:53
The problem is im not getting a Proceed to site 💯 

![image](https://user-images.githubusercontent.com/47098243/92231745-bf619480-eec6-11ea-9839-be66739e5e34.png)

**Comment by asim47** [comment] 2020-09-04 10:58
Fixed it following this article
https://medium.com/@dblazeski/chrome-bypass-net-err-cert-invalid-for-development-daefae43eb12

**Comment by asim47** [comment] 2020-09-04 11:00
new issue 
![image](https://user-images.githubusercontent.com/47098243/92232297-c5a44080-eec7-11ea-9d7b-81611c76b6a0.png)

**Comment by asim47** [comment] 2020-09-04 11:07
I'm getting trouble with something, i've follow the steps to run with the correct config, but when I join the room, after about 1 second i get the notification "Unable to Join Room" and get redirected to root page.

**Comment by pierguinzani** [comment] 2020-09-04 11:15
Follow these steps https://github.com/edumeet/edumeet/issues/529#issuecomment-683737840 and see if it solves your problem.

**Comment by asim47** [comment] 2020-09-04 11:19
@pierguinzani  Working fine now, Thank you

**Comment by pierguinzani** [comment] 2020-09-04 11:25
An alternative to solve this problem is to add this function to the
server/config/config.js
```
function getListenIps() {
  const interfaces = os.networkInterfaces();
  const addresses = [];
 
  Object.keys(interfaces).forEach((netInterface) => {
   interfaces[netInterface].forEach((interfaceObject) => {
    if (interfaceObject.family === 'IPv4' && !interfaceObject.internal) {
     addresses.push({ ip: interfaceObject.address, announcedIp: null });
    }
   });
  });
  return(addresses);
 }
```
and call the function instead of setting it manually
![image](https://user-images.githubusercontent.com/49373874/92234298-21e77000-ee88-11ea-9e3f-626eea1ac664.png)

**Comment by misi** [comment] 2020-09-27 09:48
I think here is no open question so I conclude as it is solved and close it. Please open a new issue if any open question left here.
Thanks!

**Closed by misi** 2020-09-27 09:48 UTC
Labels: question

**Comment by Vikas349** [comment] 2022-08-26 07:33
Hi,
I am getting error  "Unable to join the room". Please help!

Tell me if I am missing something?
